name: Build Anti Malware

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "java/anti-malware/*"
      - .github/workflows/anti-malware.yml

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./java/anti-malware
      file: ./java/anti-malware/Dockerfile
      tags: ghcr.io/sparkedhost/images:anti-malware
