name: Build games-aneurism-iv

on:
  push:
    branches:
      - main
    paths:
      - "games/aneurism-iv/*"
      - .github/workflows/games-aneurism-iv.yml

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./games
      file: ./games/aneurism-iv/Dockerfile
      tags: ghcr.io/sparkedhost/images:games-aneurism-iv
